### ISSUE TITLE
What platforms are supported?

### ISSUE THREAD

**Issue by cmcqueen** [Aloz1/wslua_conversation#1]
What platforms can this be expected to work on? (Windows, Linux, MacOS) It's worth mentioning in the readme.

**Comment by Aloz1** [comment]
Good point. I'll update the read-me to include that info, as well as dependency info.

I've only tested it on Linux. However, there's nothing platform specific in the code.

It should theoretically be possible to get things going anywhere that meson runs. The only dependencies are:
- meson
- C compiler (dependent on platform)
- lua 5.2 headers
- Wireshark headers

I've never used meson before on Windows, so I couldn't tell you how hard it would be to setup.

For Unix based platforms (macOS, *BSD, Solaris) it should be fairly trivial to get up and going.

**Comment by Aloz1** [comment]
@cmcqueen could you please have a quick read over this, and let me know if you're happy with the additional info in the README?

**Comment by cmcqueen** [comment]
Thanks, that information is helpful to know.

I may or may not get a chance to try this on a Windows platform for work (depends on work project schedules). If I do, I'll try to feed back any useful information about what was required on that platform.
